services:
  web:
    image: wabot-app:latest
    build:
      context: .
    restart: always
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/wabot_bsp?schema=public
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  worker:
    image: wabot-app:latest
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/wabot_bsp?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    command: npx tsx worker.ts

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wabot_bsp
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data_prod:/data

volumes:
  postgres_data_prod:
  redis_data_prod:
