
services:
  postgres:
    image: ankane/pgvector:v0.5.1-pg15
    container_name: grafty_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grafty_bsp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - grafty

  redis:
    image: redis:7-alpine
    container_name: grafty_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - grafty

networks:
  grafty:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
