#!/usr/bin/expect -f
set SERVER    "root@72.61.231.187"
set PASS      "Photoshop09@"
set timeout   -1

puts "\n🚀 Syncing files..."
spawn rsync -avzc --exclude="node_modules" --exclude=".git" --exclude=".env" ./ $SERVER:/root/grafty_bsp/
expect {
    "password:" { send "$PASS\r"; exp_continue }
    eof
}

puts "\n🚀 Rebuilding (No Cache for builder)..."
spawn ssh -o StrictHostKeyChecking=no $SERVER "cd /root/grafty_bsp && docker compose -f docker-compose.prod.yml build --no-cache && docker compose -f docker-compose.prod.yml up -d"
expect {
    "password:" { send "$PASS\r"; exp_continue }
    eof
}
