import { prisma } from "../db";

export class GoogleCalendarService {
    private static GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token";
    private static CALENDAR_API_URL = "https://www.googleapis.com/calendar/v3/calendars/primary/events";

    /**
     * Retrieves and refreshes the Google Calendar access token for a workspace.
     */
    private static async getValidAccessToken(workspaceId: string): Promise<string> {
        const integration = await prisma.integration.findUnique({
            where: { workspace_id_type: { workspace_id: workspaceId, type: "GOOGLE_CALENDAR" } }
        });

        if (!integration || !integration.is_active) {
            throw new Error("Google Calendar integration not found or inactive for this workspace.");
        }

        const creds = integration.credentials as any;

        // Check if token is expired (adding 1-minute buffer)
        if (creds.expiry_date && creds.expiry_date > Date.now() + 60000) {
            return creds.access_token;
        }

        console.log(`[Google Calendar] Refreshing token for workspace: ${workspaceId}`);

        if (!creds.refresh_token) {
            throw new Error("No refresh token available. Please reconnect your Google Calendar.");
        }

        const res = await fetch(this.GOOGLE_TOKEN_URL, {
            method: "POST",
            headers: { "Content-Type": "application/x-www-form-urlencoded" },
            body: new URLSearchParams({
                client_id: process.env.GOOGLE_CLIENT_ID!,
                client_secret: process.env.GOOGLE_CLIENT_SECRET!,
                refresh_token: creds.refresh_token,
                grant_type: "refresh_token",
            }),
        });

        const data = await res.json();
        if (data.error) {
            console.error("[Google Calendar] Token refresh failed:", data.error, data.error_description);
            // Deactivate integration if refresh token is invalid
            if (data.error === "invalid_grant") {
                await prisma.integration.update({
                    where: { id: integration.id },
                    data: { is_active: false }
                });
            }
            throw new Error(`Failed to refresh Google token: ${data.error}`);
        }

        const newAccessToken = data.access_token;
        const newExpiryDate = Date.now() + (data.expires_in * 1000);

        // Persist the new tokens
        await prisma.integration.update({
            where: { id: integration.id },
            data: {
                credentials: {
                    ...creds,
                    access_token: newAccessToken,
                    expiry_date: newExpiryDate,
                }
            }
        });

        return newAccessToken;
    }

    /**
     * Creates a Google Meet meeting and returns the URL.
     */
    public static async createInstantMeeting(workspaceId: string, summary: string = "Quick Sync"): Promise<string> {
        const accessToken = await this.getValidAccessToken(workspaceId);

        const now = new Date();
        const endTime = new Date(now.getTime() + 30 * 60 * 1000); // 30 min duration

        const eventData = {
            summary,
            description: "Generated by Grafty BSP",
            start: {
                dateTime: now.toISOString(),
                timeZone: "Asia/Kolkata",
            },
            end: {
                dateTime: endTime.toISOString(),
                timeZone: "Asia/Kolkata",
            },
            conferenceData: {
                createRequest: {
                    requestId: `grafty-${Date.now()}`,
                    conferenceSolutionKey: {
                        type: "hangoutsMeet",
                    },
                },
            },
        };

        const res = await fetch(`${this.CALENDAR_API_URL}?conferenceDataVersion=1`, {
            method: "POST",
            headers: {
                Authorization: `Bearer ${accessToken}`,
                "Content-Type": "application/json",
            },
            body: JSON.stringify(eventData),
        });

        const data = await res.json();

        if (data.error) {
            console.error("[Google Calendar] Event creation failed:", data.error);
            throw new Error(`Google Calendar Error: ${data.error.message || "Failed to create meeting"}`);
        }

        // Extract the Meet link (hangoutLink)
        return data.hangoutLink;
    }
}
