import { NextResponse } from "next/server";
import nodemailer from "nodemailer";
import { getResellerSession } from "../../../../../lib/reseller/auth-helper";

export async function POST(req: Request) {
    try {
        const session = await getResellerSession();
        if (!session) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        const body = await req.json();
        const { smtp_config } = body;

        if (!smtp_config || !smtp_config.host || !smtp_config.port || !smtp_config.user || !smtp_config.pass) {
            return NextResponse.json({ error: "Incomplete SMTP Configuration" }, { status: 400 });
        }

        // Create transporter with provided config
        const transporter = nodemailer.createTransport({
            host: smtp_config.host,
            port: Number(smtp_config.port),
            secure: Number(smtp_config.port) === 465,
            auth: {
                user: smtp_config.user,
                pass: smtp_config.pass,
            },
        });

        // Verify connection configuration
        try {
            await transporter.verify();
        } catch (verifyError: any) {
            console.error("SMTP Verify Error:", verifyError);
            return NextResponse.json({ error: `Connection failed: ${verifyError.message}` }, { status: 400 });
        }

        // Attempt to send a test email
        const mailOptions = {
            from: smtp_config.from_email || smtp_config.user,
            to: smtp_config.from_email || smtp_config.user,
            subject: "Branding Terminal: SMTP Security Verification",
            text: `SMTP Configuration successfully verified for your partner account.\n\nHost: ${smtp_config.host}\nPort: ${smtp_config.port}\nUser: ${smtp_config.user}\n\nThis is a system-generated test message.`,
            html: `
                <div style="font-family: sans-serif; padding: 40px; background: #f8fafc;">
                    <div style="max-width: 600px; margin: 0 auto; background: white; border-radius: 24px; padding: 40px; border: 1px solid #e2e8f0; box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1);">
                        <h1 style="color: #0f172a; font-size: 24px; font-weight: 800; margin-bottom: 8px;">SMTP Verified</h1>
                        <p style="color: #64748b; font-size: 14px; margin-bottom: 32px;">Your outbound mail server is successfully connected to the Branding Terminal.</p>
                        
                        <div style="background: #f1f5f9; padding: 24px; border-radius: 16px; margin-bottom: 32px;">
                            <div style="margin-bottom: 8px;"><strong style="font-size: 10px; text-transform: uppercase; color: #94a3b8; letter-spacing: 0.1em;">Host</strong></div>
                            <div style="color: #334155; font-weight: 700;">${smtp_config.host}</div>
                        </div>

                        <p style="color: #94a3b8; font-size: 12px; font-style: italic;">This is a security verification email generated by Grafty.</p>
                    </div>
                </div>
            `
        };

        await transporter.sendMail(mailOptions);

        return NextResponse.json({ success: true, message: "Test email sent successfully" });

    } catch (error: any) {
        console.error("SMTP Test Error:", error);
        return NextResponse.json({ error: error.message || "Failed to send test email" }, { status: 500 });
    }
}
